BASE   = ../..
NAME   = lib$(shell basename `pwd`)
OUTPUT = $(BASE)/lib/$(NAME).so
-include $(BASE)/make-config

ifndef MLR_RoboticsCourse
GTK = 1
GTKGL = 1
FREEGLUT = 0
QHULL = 1
GRAPHVIZ = 1
GJK = 1
LEWINER = 1
PLY = 1
DEPEND = Core
else
QHULL = 1
FREEGLUT = 1
DEPEND = Core
endif

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/gofMake/generic.mk
